### ISSUE TITLE
Come up with balanced dispositions and ages

### ISSUE THREAD

**Issue by Renddslow** [Renddslow/dunsany#1]
We have two main categories for pantheons: age and disposition. 

The thought is **disposition** would affect how players/npc cultures would interact with a given pantheon. Perhaps a certain pantheon is more deistic, they set things running, will let you borrow their magic on the whole, but really don't care about humans. On the other hand, you may have a pantheon that by and large demands piety (think Faith of the Seven vs Old Gods).

**Age** on the other hand would more likely affect the pantheon's relationship to other pantheons.

Both of these things need sussed out and need to be thought through in terms of how they will help/hinder balance at the cosmic level.

**Comment by SkaffenAmtiskaw** [comment]
I think another aspect I've been playing around with in my head is some deities (or pantheons?) might really want to help individual factions (each player controlling a faction) who worship them whereas other deities/pantheons might be more concerned about balance between factions and want to prevent any one faction from growing too powerful. Others might be entirely unconcerned with factional balance and want to prevent factions from say, overuse of the environment or something similar.

**Comment by Renddslow** [comment]
I really like that idea. So how do we codify that meaningfully? Do we add categories for that, or do we just make that part of the disposition?
And with that in mind, do we make some sort of dispositional matrix. Think the d20 alignment. Essentially an individual deity could only be one step in any direction from their pantheon's disposition.

| Realm | Protective | Apathetic | Hostile | Balanced |
| --- | --- | --- | --- | --- |
| Human | | | | |
| Nature | | | | |
| Balance | | | | |
| Dead |  | | | |

**Comment by SkaffenAmtiskaw** [comment]
I _really_ like the idea that an individual deity is constrained by their pantheon but there can still be meaningful differences.

I kind of think of it as two different axes which I am having trouble naming but roughly correspond to level of concern/interference they think is appropriate and the specificity of this concern/interference.

High Interference/Non-Specific -> They are very interested in the fate of the world, but do not have one overarching concern. They will respond instinctively to events based on their current preoccupations and will be somewhat unpredictable as a result.

Low Interference/Non-Specific -> They are generally almost entirely uninterested in the fate of mortals. This does not necessarily mean they aren't interested in the affairs of other gods however, so their actions will sometimes indirectly impact mortals.

High Interference/Specific -> They have a specific concern they want to advance in the realm of mortals. This could be the fate of a faction, the fate of an individual or race, or achieving balance between all factions. They will consistently act to advance this interest.

Low Interference/Specific -> If pushed (generally by other gods) they will act in the interests of a specific concern, but they will generally not interfere. This can also include gods who cannot interfere for some reason.

**Comment by Renddslow** [comment]
So I know we're planning to discuss this further. But a note so I don't forget. I like the idea of deities having meaningful differences. That said, I also like the idea that every so often (by roll) you could have a rogue deity. So as we're landing dispositions/alignments, whatever we're calling them, they could roll a rogue and just have a completely different disposition.

Largely depends on if we're doing spectrum, axis, or matrix at some level

**Comment by Renddslow** [comment]
![chart](https://user-images.githubusercontent.com/12091479/72005315-f043d980-3212-11ea-8c31-60f69f781c2a.png)
