### ISSUE TITLE
Family Tree

### ISSUE THREAD

**Issue by Renddslow** [Renddslow/dunsany#3]
We need to develop rules around generating family trees. The following comments will outline the rules we determined.

**Comment by Renddslow** [comment]
![family-tree](https://user-images.githubusercontent.com/12091479/72007986-79114400-3218-11ea-975b-1b22ea69937a.png)

**Comment by Renddslow** [comment]
## Set up
1. Always start with a chief god/goddess
2. Generate a side board of deities who were birthed by other titans (< 10)
3. Determine each side board member's relationship to chief
4. Generate chief spouse if not herm/matriarch

## Rules
1. Randomly generate consort nodes against each potential suitor of chief and chief spouse. Some of these nodes will be anonymous nodes, as surely the cosmos doesn't care about recording every cow, chicken, or milkmaid that a god has slept with. 
2. Each consort node produces a random number of child deities. Each consort node should weight random number such that having more than 3 children becomes increasingly rare.
3. With the second generation now created each member of that generation has the option to hookup. For each member of the second generation, randomly create consort nodes against every living deity which is not the child of an anonymous consort. Randomly create anonymous consort nodes for each second generation deity as well.
4. Produce children from each new consort node.

This should create a sizable pantheon with a handful of demigods. **note to self**: demigods should have their archetype removed and replaced with `"demi"`

**Comment by SkaffenAmtiskaw** [comment]
I believe the rules for demigods were (a) they are the descendants of a deity and a mortal and (b) their children will be purely mortal. From a lore standpoint, I think the rule would be that not every "hook-up" between a deity and a mortal results in a demigod, but that's not really relevant for pantheon creation purposes.

**Comment by Renddslow** [comment]
So in other words, the ones we create through [dunsany](https://github.com/Renddslow/dunsany) are strictly the offspringer that _are_ demigods. There may have been other children but we don't care?
